stages:
  - build
  - deploy

build-back:
  stage: build
  only:
    - master
    - develop
  script:
    - cd $CI_PROJECT_DIR/backend
    - ls
    - chmod +x gradlew
    - mkdir ./src/main/resources
    - cp /home/gitlab-runner/builds/S9GN1Npi/0/s06-bigdata-rec-sub2/S06P22D105.tmp/APPLICATION ./src/main/resources/application.yml
    - ls -al ./src/main/resources
    - cat ./src/main/resources/application.yml
    - ./gradlew build
    # cp 배포 파일 옮기기


  tags:
    - prd

build-front:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - S06P22D105/frontend/node_modules
  only:
    - master
    - develop
  script:
    - cd $CI_PROJECT_DIR/frontend
    - cp /home/gitlab-runner/builds/S9GN1Npi/0/s06-bigdata-rec-sub2/S06P22D105.tmp/FRONTEND_ENV ./.env
    - rm -rf package-lock.json
    - npm install
    - CI=false npm run build
    - sudo rm -rf /home/ubuntu/S06P22D105/frontend/build
    - sudo cp -rf build /home/ubuntu/S06P22D105/frontend

  tags:
    - prd

deploy-back:
  stage: deploy
  only:
    - master
    - develop
  script:
    # 백엔드 재시작 스크립트 작성
    - ls
  tags:
    - prd

deploy-front:
  stage: deploy
  only:
    - master
    - develop
  script:
    # 프론트 재시작 스크립트 작성
    - ls -al ~/project/S06P22D105/frontend/build
  tags:
    - prd
