stages:
    - build
    - deploy

build-back:
    stage : build
    only :
        - master
        - develop
    script : 
        - cd $CI_PROJECT_DIR/backend
        - ls
        - chmod +x gradlew
        # - ./gradlew build
        - cd ./src/main
        - mkdir resources
        - ls
        - cd ./resources
        # - echo $APPLICATION
        - cp /home/gitlab-runner/builds/S9GN1Npi/0/s06-bigdata-rec-sub2/S06P22D105.tmp/APPLICATION ./application.yml
        - ls
        # cp 배포 파일 옮기기

    tags :
        - prd

build-front:
    stage : build
    cache :
        key : ${CI_COMMIT_REF_SLUG}
        paths : 
            - S06P22D105/frontend/node_modules
    only : 
        - master
        - develop
    script :
        - cd $CI_PROJECT_DIR/frontend
        - pwd
        - rm -rf package-lock.json
        - ls
        - npm install
        - CI=false npm run build
        # - cd ./build
        - ls
        - pwd
        - ls ~/S06P22D105/frontend
        - rm -rf ~/S06P22D105/frontend/build
        # - cp -rf build ~/S06P22D105/frontend
        
    tags : 
        - prd

    
deploy-back:
    stage: deploy
    only : 
        - master
        - develop
    script : 
        # 백엔드 재시작 스크립트 작성
        - ls
    tags:
        - prd

deploy-front:
    stage: deploy
    only :
        - master
        - develop
    script:
        # 프론트 재시작 스크립트 작성
        - ls -al ~/project/S06P22D105/front/build
    tags :
        - prd