stages:
  - build
  - deploy

build-back:
  stage: build
  only:
    - master
    - develop

  before_script:
    - cd $CI_PROJECT_DIR/backend
    - mkdir ./src/main/resources
    # - rm -rf build.gradle
    # - cp /home/gitlab-runner/builds/S9GN1Npi/0/s06-bigdata-rec-sub2/S06P22D105.tmp/BUILD_GRADLE ./build.gradle
    - cp /home/gitlab-runner/builds/S9GN1Npi/0/s06-bigdata-rec-sub2/S06P22D105.tmp/APPLICATION ./src/main/resources/application.yml
    - rm -rf ./src/main/java/com/ladder/perfumism/global/config/WebSecurityConfig.java
    - cp /home/gitlab-runner/builds/S9GN1Npi/0/s06-bigdata-rec-sub2/S06P22D105.tmp/WEBSECURITY ./src/main/java/com/ladder/perfumism/global/config/WebSecurityConfig.java
    - ls -al ./src/main/resources

  script:
    - cd $CI_PROJECT_DIR/backend
    - ls
    - chmod +x gradlew
    - ./gradlew build

  after_script:
    - cd $CI_PROJECT_DIR/backend
    - sudo rm -rf /home/ubuntu/S06P22D105/backend/build
    - sudo cp -rf build /home/ubuntu/S06P22D105/backend

  tags:
    - prd

build-data:
  stage: build
  only:
    - master
    - develop

  before_script:
    - cd $CI_PROJECT_DIR/data
    - echo "데이터 빌드 시작"
    - ls

  script:
    - cd $CI_PROJECT_DIR/data
    - pwd

  after_script:
    - cd $CI_PROJECT_DIR/data
    - echo "데이터 빌드 끝"

  tags:
    - prd

build-front:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - S06P22D105/frontend/node_modules
  only:
    - master
    - develop

  before_script:
    - cd $CI_PROJECT_DIR/frontend
    - cp /home/gitlab-runner/builds/S9GN1Npi/0/s06-bigdata-rec-sub2/S06P22D105.tmp/FRONTEND_ENV ./.env
    - rm -rf package-lock.json

  script:
    - cd $CI_PROJECT_DIR/frontend
    - npm install
    - CI=false npm run build

  after_script:
    - cd $CI_PROJECT_DIR/frontend
    - sudo rm -rf /home/ubuntu/S06P22D105/frontend/build
    - sudo cp -rf build /home/ubuntu/S06P22D105/frontend

  tags:
    - prd

deploy-back:
  stage: deploy
  only:
    - master
    - develop
  before_script:
    - echo "백 배포 시작"
  script:
    - cd /home/ubuntu
    - sudo ./restart_backend.sh
  after_script:
    - echo "백 배포 끝"
  tags:
    - prd

deploy-data:
  stage: deploy
  only:
    - master
    - develop

  before_script:
    - cd $CI_PROJECT_DIR/data
    - echo "데이터 배포 시작"
    - ls

  script:
    - cd $CI_PROJECT_DIR/data
    - pwd

  after_script:
    - cd $CI_PROJECT_DIR/data
    - echo "데이터 배포 끝"

  tags:
    - prd

deploy-front:
  stage: deploy
  only:
    - master
    - develop
  before_script:
    - echo "프론트 배포 시작"
  script:
    - ls -al /home/ubuntu/S06P22D105/frontend/build
    - cd /home/ubuntu/
    - sudo ./restart_frontend.sh
  after_script:
    - echo "프론트 배포 끝"
  tags:
    - prd
